[build.nixpacksPlan.phases.setup]
nixPkgs = ["chromium", "nodejs_20"]

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[build.nixpacksPlan.phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
dependsOn = ["build"]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium/bin/chromium"
